---
- name: Openstack Launch VM
  hosts: localhost
  tasks:
  - name: Create a new instance and attaches to a network
    openstack.cloud.server:
       state: present
       name: vm1
       image: CENTOS-7
       timeout: 200
       flavor: 1ec12e57-797d-487b-a68c-fd7e21542001
       nics:
         - net-id: f7713285-da22-4844-8c8b-050323a4de7d
       meta:
         hostname: test1
